// --- Master Game Configuration (Final Refined List) ---
const MASTER_CONFIG = [
    // -- Animals --
    { name: 'ant',        emoji: '🐜', category: 'animal' },
    { name: 'bear',       emoji: '🐻', category: 'animal', color: 'brown' },
    { name: 'cat',        emoji: '🐱', category: 'animal', color: 'orange' },
    { name: 'dog',        emoji: '🐶', category: 'animal', color: 'brown' },
    { name: 'duck',       emoji: '🦆', category: 'animal', color: 'yellow' },
    { name: 'elephant',   emoji: '🐘', category: 'animal', color: 'gray' },
    { name: 'fox',        emoji: '🦊', category: 'animal', color: 'orange' },
    { name: 'frog',       emoji: '🐸', category: 'animal', color: 'green' },
    { name: 'gorilla',    emoji: '🦍', category: 'animal', color: 'black' },
    { name: 'hamster',    emoji: '🐹', category: 'animal', color: 'brown' },
    { name: 'horse',      emoji: '🐴', category: 'animal', color: 'brown' },
    { name: 'kangaroo',   emoji: '🦘', category: 'animal', color: 'brown' },
    { name: 'koala',      emoji: '🐨', category: 'animal', color: 'gray' },
    { name: 'leopard',    emoji: '🐆', category: 'animal', color: 'yellow' },
    { name: 'lion',       emoji: '🦁', category: 'animal', color: 'yellow' },
    { name: 'monkey',     emoji: '🐒', category: 'animal', color: 'brown' },
    { name: 'mouse',      emoji: '🐭', category: 'animal', color: 'gray' },
    { name: 'octopus',    emoji: '🐙', category: 'animal', color: 'purple' },
    { name: 'owl',        emoji: '🦉', category: 'animal', color: 'brown' },
    { name: 'panda',      emoji: '🐼', category: 'animal', color: 'white' },
    { name: 'peacock',    emoji: '🦚', category: 'animal', color: 'blue' },
    { name: 'penguin',    emoji: '🐧', category: 'animal', color: 'black' },
    { name: 'pig',        emoji: '🐷', category: 'animal', color: 'pink' },
    { name: 'rabbit',     emoji: '🐰', category: 'animal', color: 'white' },
    { name: 'raccoon',    emoji: '🦝', category: 'animal', color: 'gray' },
    { name: 'rooster',    emoji: '🐓', category: 'animal' },
    { name: 'shark',      emoji: '🦈', category: 'animal', color: 'gray' },
    { name: 'sheep',      emoji: '🐑', category: 'animal', color: 'white' },
    { name: 'sloth',      emoji: '🦥', category: 'animal', color: 'brown' },
    { name: 'snake',      emoji: '🐍', category: 'animal', color: 'green' },
    { name: 'squirrel',   emoji: '🐿️', category: 'animal', color: 'brown' },
    { name: 'tiger',      emoji: '🐅', category: 'animal', color: 'orange' },
    { name: 'turkey',     emoji: '🦃', category: 'animal', color: 'brown' },
    { name: 'turtle',     emoji: '🐢', category: 'animal', color: 'green' },
    { name: 'unicorn',    emoji: '🦄', category: 'animal', color: 'white' },
    { name: 'whale',      emoji: '🐳', category: 'animal', color: 'blue' },
    { name: 'wolf',       emoji: '🐺', category: 'animal', color: 'gray' },
    { name: 'zebra',      emoji: '🦓', category: 'animal', color: 'white' },

    // -- Fruits & Vegetables --
    { name: 'apple',      emoji: '🍎', category: 'fruit',   color: 'red' },
    { name: 'avocado',    emoji: '🥑', category: 'fruit',   color: 'green' },
    { name: 'banana',     emoji: '🍌', category: 'fruit',   color: 'yellow' },
    { name: 'broccoli',   emoji: '🥦', category: 'vegetable', color: 'green' },
    { name: 'carrot',     emoji: '🥕', category: 'vegetable', color: 'orange' },
    { name: 'cherries',   emoji: '🍒', category: 'fruit',   color: 'red' },
    { name: 'coconut',    emoji: '🥥', category: 'fruit',   color: 'brown' },
    { name: 'corn',       emoji: '🌽', category: 'vegetable', color: 'yellow' },
    { name: 'cucumber',   emoji: '🥒', category: 'vegetable', color: 'green' },
    { name: 'eggplant',   emoji: '🍆', category: 'vegetable', color: 'purple' },
    { name: 'garlic',     emoji: '🧄', category: 'vegetable', color: 'white' },
    { name: 'grapes',     emoji: '🍇', category: 'fruit',   color: 'purple' },
    { name: 'kiwi',       emoji: '🥝', category: 'fruit',   color: 'brown' },
    { name: 'lemon',      emoji: '🍋', category: 'fruit',   color: 'yellow' },
    { name: 'lettuce',    emoji: '🥬', category: 'vegetable', color: 'green' },
    { name: 'mango',      emoji: '🥭', category: 'fruit',   color: 'orange' },
    { name: 'melon',      emoji: '🍈', category: 'fruit',   color: 'green' },
    { name: 'mushroom',   emoji: '🍄', category: 'vegetable', color: 'red' },
    { name: 'onion',      emoji: '🧅', category: 'vegetable', color: 'brown' },
    { name: 'orange',     emoji: '🍊', category: 'fruit',   color: 'orange' },
    { name: 'peach',      emoji: '🍑', category: 'fruit',   color: 'orange' },
    { name: 'pear',       emoji: '🍐', category: 'fruit',   color: 'green' },
    { name: 'pineapple',  emoji: '🍍', category: 'fruit',   color: 'yellow' },
    { name: 'potato',     emoji: '🥔', category: 'vegetable', color: 'brown' },
    { name: 'strawberry', emoji: '🍓', category: 'fruit',   color: 'red' },
    { name: 'tomato',     emoji: '🍅', category: 'fruit',   color: 'red' },
    { name: 'watermelon', emoji: '🍉', category: 'fruit',   color: 'green' },

    // -- Food & Drink --
    { name: 'bacon',      emoji: '🥓', category: 'food' },
    { name: 'bagel',      emoji: '🥯', category: 'food' },
    { name: 'bread',      emoji: '🍞', category: 'food', color: 'brown' },
    { name: 'burrito',    emoji: '🌯', category: 'food' },
    { name: 'cake',       emoji: '🎂', category: 'food', color: 'pink' },
    { name: 'candy',      emoji: '🍬', category: 'food' },
    { name: 'cheese',     emoji: '🧀', category: 'food', color: 'yellow' },
    { name: 'chocolate',  emoji: '🍫', category: 'food', color: 'brown' },
    { name: 'cookie',     emoji: '🍪', category: 'food', color: 'brown' },
    { name: 'croissant',  emoji: '🥐', category: 'food' },
    { name: 'cupcake',    emoji: '🧁', category: 'food' },
    { name: 'donut',      emoji: '🍩', category: 'food' },
    { name: 'egg',        emoji: '🥚', category: 'food', color: 'white' },
    { name: 'fries',      emoji: '🍟', category: 'food' },
    { name: 'hamburger',  emoji: '🍔', category: 'food' },
    { name: 'honey',      emoji: '🍯', category: 'food', color: 'yellow' },
    { name: 'hotdog',     emoji: '🌭', category: 'food' },
    { name: 'ice cream',  emoji: '🍦', category: 'food', color: 'white' },
    { name: 'juice',      emoji: '🧃', category: 'drink' },
    { name: 'lollipop',   emoji: '🍭', category: 'food' },
    { name: 'milk',       emoji: '🥛', category: 'drink', color: 'white' },
    { name: 'pancakes',   emoji: '🥞', category: 'food' },
    { name: 'pie',        emoji: '🥧', category: 'food' },
    { name: 'pizza',      emoji: '🍕', category: 'food' },
    { name: 'popcorn',    emoji: '🍿', category: 'food' },
    { name: 'pretzel',    emoji: '🥨', category: 'food' },
    { name: 'rice',       emoji: '🍚', category: 'food' },
    { name: 'sandwich',   emoji: '🥪', category: 'food' },
    { name: 'steak',      emoji: '🥩', category: 'food' },
    { name: 'sushi',      emoji: '🍣', category: 'food' },
    { name: 'taco',       emoji: '🌮', category: 'food' },
    { name: 'tea',        emoji: '🍵', category: 'drink', color: 'green' },

    // -- Objects & Tools --
    { name: 'alarm clock',emoji: '⏰', category: 'object', color: 'red' },
    { name: 'axe',        emoji: '🪓', category: 'tool' },
    { name: 'balloon',    emoji: '🎈', category: 'object', color: 'red' },
    { name: 'battery',    emoji: '🔋', category: 'object', color: 'green' },
    { name: 'bell',       emoji: '🔔', category: 'object', color: 'yellow' },
    { name: 'bomb',       emoji: '💣', category: 'object', color: 'black' },
    { name: 'books',      emoji: '📚', category: 'object' },
    { name: 'broom',      emoji: '🧹', category: 'tool' },
    { name: 'bucket',     emoji: '🪣', category: 'object' },
    { name: 'calendar',   emoji: '📅', category: 'object' },
    { name: 'camera',     emoji: '📷', category: 'object' },
    { name: 'candle',     emoji: '🕯️', category: 'object' },
    { name: 'chair',      emoji: '🪑', category: 'object', color: 'brown' },
    { name: 'compass',    emoji: '🧭', category: 'tool' },
    { name: 'computer',   emoji: '💻', category: 'object' },
    { name: 'couch',      emoji: '🛋️', category: 'object', color: 'blue' },
    { name: 'crayon',     emoji: '🖍️', category: 'tool', color: 'red' },
    { name: 'crown',      emoji: '👑', category: 'object', color: 'yellow' },
    { name: 'crystal ball',emoji: '🔮', category: 'object', color: 'purple' },
    { name: 'diamond',    emoji: '💎', category: 'object', color: 'blue' },
    { name: 'door',       emoji: '🚪', category: 'object', color: 'brown' },
    { name: 'drum',       emoji: '🥁', category: 'instrument' },
    { name: 'envelope',   emoji: '✉️', category: 'object' },
    { name: 'fire extinguisher', emoji: '🧯', category: 'tool', color: 'red' },
    { name: 'flashlight', emoji: '🔦', category: 'tool' },
    { name: 'gift',       emoji: '🎁', category: 'object', color: 'red' },
    { name: 'globe',      emoji: '🌎', category: 'object', color: 'blue' },
    { name: 'hammer',     emoji: '🔨', category: 'tool' },
    { name: 'key',        emoji: '🔑', category: 'tool', color: 'yellow' },
    { name: 'keyboard',   emoji: '⌨️', category: 'object' },
    { name: 'lamp',       emoji: '💡', category: 'object' },
    { name: 'lock',       emoji: '🔒', category: 'object', color: 'gray' },
    { name: 'magnet',     emoji: '🧲', category: 'tool', color: 'red' },
    { name: 'magnifying glass', emoji: '🔎', category: 'tool' },
    { name: 'map',        emoji: '🗺️', category: 'object' },
    { name: 'microphone', emoji: '🎤', category: 'object' },
    { name: 'microscope', emoji: '🔬', category: 'tool' },
    { name: 'money',      emoji: '💵', category: 'object', color: 'green' },
    { name: 'newspaper',  emoji: '📰', category: 'object' },
    { name: 'notebook',   emoji: '📓', category: 'object' },
    { name: 'package',    emoji: '📦', category: 'object', color: 'brown' },
    { name: 'paintbrush', emoji: '🖌️', category: 'tool' },
    { name: 'paperclip',  emoji: '📎', category: 'object' },
    { name: 'pencil',     emoji: '✏️', category: 'tool', color: 'yellow' },
    { name: 'phone',      emoji: '📱', category: 'object'},
    { name: 'piano',      emoji: '🎹', category: 'instrument' },
    { name: 'pin',        emoji: '📌', category: 'object', color: 'red' },
    { name: 'radio',      emoji: '📻', category: 'object' },
    { name: 'ring',       emoji: '💍', category: 'object' },
    { name: 'ruler',      emoji: '📏', category: 'tool' },
    { name: 'satellite',  emoji: '📡', category: 'object' },
    { name: 'saxophone',  emoji: '🎷', category: 'instrument' },
    { name: 'scissors',   emoji: '✂️', category: 'tool', color: 'red' },
    { name: 'screw',      emoji: '🔩', category: 'tool' },
    { name: 'soap',       emoji: '🧼', category: 'object' },
    { name: 'telescope',  emoji: '🔭', category: 'tool' },
    { name: 'television', emoji: '📺', category: 'object' },
    { name: 'toilet paper', emoji: '🧻', category: 'object', color: 'white' },
    { name: 'toothbrush', emoji: '🪥', category: 'object' },
    { name: 'trophy',     emoji: '🏆', category: 'object', color: 'yellow' },
    { name: 'trumpet',    emoji: '🎺', category: 'instrument' },
    { name: 'violin',     emoji: '🎻', category: 'instrument' },
    { name: 'wrench',     emoji: '🔧', category: 'tool' },

    // -- Vehicles --
    { name: 'ambulance',  emoji: '🚑', category: 'vehicle' },
    { name: 'airplane',   emoji: '✈️', category: 'vehicle' },
    { name: 'bicycle',    emoji: '🚲', category: 'vehicle' },
    { name: 'bus',        emoji: '🚌', category: 'vehicle', color: 'yellow' },
    { name: 'car',        emoji: '🚗', category: 'vehicle', color: 'red' },
    { name: 'helicopter', emoji: '🚁', category: 'vehicle' },
    { name: 'motorcycle', emoji: '🏍️', category: 'vehicle' },
    { name: 'police car', emoji: '🚓', category: 'vehicle' },
    { name: 'rocket',     emoji: '🚀', category: 'vehicle' },
    { name: 'ship',       emoji: '🚢', category: 'vehicle' },
    { name: 'taxi',       emoji: '🚕', category: 'vehicle', color: 'yellow' },
    { name: 'tractor',    emoji: '🚜', category: 'vehicle', color: 'green' },
    { name: 'train',      emoji: '🚂', category: 'vehicle' },
    { name: 'truck',      emoji: '🚚', category: 'vehicle', color: 'blue' },

    // -- Nature & Weather --
    { name: 'cactus',     emoji: '🌵', category: 'plant', color: 'green' },
    { name: 'cloud',      emoji: '☁️', category: 'weather', color: 'white' },
    { name: 'comet',      emoji: '☄️', category: 'nature' },
    { name: 'earth',      emoji: '🌍', category: 'nature' },
    { name: 'fire',       emoji: '🔥', category: 'nature', color: 'orange' },
    { name: 'flower',     emoji: '🌸', category: 'plant', color: 'pink' },
    { name: 'leaf',       emoji: '🍁', category: 'plant', color: 'red' },
    { name: 'moon',       emoji: '🌙', category: 'nature', color: 'yellow' },
    { name: 'mountain',   emoji: '⛰️', category: 'nature' },
    { name: 'rainbow',    emoji: '🌈', category: 'weather' },
    { name: 'rock',       emoji: '🪨', category: 'nature', color: 'gray' },
    { name: 'snowflake',  emoji: '❄️', category: 'weather', color: 'blue' },
    { name: 'star',       emoji: '⭐', category: 'nature', color: 'yellow' },
    { name: 'sun',        emoji: '☀️', category: 'nature', color: 'yellow' },
    { name: 'tree',       emoji: '🌳', category: 'plant', color: 'green' },
    { name: 'umbrella',   emoji: '☂️', category: 'object' },
    { name: 'volcano',    emoji: '🌋', category: 'nature' },
    { name: 'water drop', emoji: '💧', category: 'nature', color: 'blue' },
    { name: 'wave',       emoji: '🌊', category: 'nature', color: 'blue' },

    // -- Sports & Activities --
    { name: 'baseball',   emoji: '⚾', category: 'sport', color: 'white' },
    { name: 'basketball', emoji: '🏀', category: 'sport', color: 'orange' },
    { name: 'bowling',    emoji: '🎳', category: 'sport' },
    { name: 'boxing glove',emoji: '🥊', category: 'sport', color: 'red' },
    { name: 'fishing pole',emoji: '🎣', category: 'sport' },
    { name: 'football',   emoji: '🏈', category: 'sport', color: 'brown' },
    { name: 'golf',       emoji: '⛳', category: 'sport' },
    { name: 'hockey',     emoji: '🏒', category: 'sport' },
    { name: 'kite',       emoji: '🪁', category: 'activity' },
    { name: 'medal',      emoji: '🏅', category: 'sport', color: 'yellow' },
    { name: 'puzzle',     emoji: '🧩', category: 'activity' },
    { name: 'running',    emoji: '🏃', category: 'sport' },
    { name: 'skateboard', emoji: '🛹', category: 'sport' },
    { name: 'ski',        emoji: '🎿', category: 'sport' },
    { name: 'soccer ball',emoji: '⚽', category: 'sport', color: 'white' },
    { name: 'tennis',     emoji: '🎾', category: 'sport', },
    { name: 'volleyball', emoji: '🏐', category: 'sport' },
    { name: 'yo-yo',      emoji: '🪀', category: 'activity' },

    // -- Clothing --
    { name: 'dress',      emoji: '👗', category: 'clothing', color: 'blue' },
    { name: 'glasses',    emoji: '👓', category: 'clothing' },
    { name: 'gloves',     emoji: '🧤', category: 'clothing' },
    { name: 'hat',        emoji: '👒', category: 'clothing' },
    { name: 'jeans',      emoji: '👖', category: 'clothing', color: 'blue' },
    { name: 'scarf',      emoji: '🧣', category: 'clothing' },
    { name: 'shirt',      emoji: '👕', category: 'clothing', color: 'blue' },
    { name: 'shoe',       emoji: '👟', category: 'clothing' },
    { name: 'sock',       emoji: '🧦', category: 'clothing' },
    
    // -- Symbols & Shapes --
    { name: 'arrow',      emoji: '➡️', category: 'symbol' },
    { name: 'circle',     emoji: '🔴', category: 'shape', color: 'red' },
    { name: 'heart',      emoji: '❤️', category: 'shape', color: 'red' },
    { name: 'question mark', emoji: '❓', category: 'symbol' },
    { name: 'square',     emoji: '🟧', category: 'shape', color: 'orange' },
    { name: 'star',       emoji: '⭐', category: 'shape', color: 'yellow' }
];